name: Build and Deploy to Github Pages

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
            ${{ runner.os }}-

      - name: Test Jekyll Pages
        uses: helaili/jekyll-action@v2
        env:
          JEKYLL_PAT: ${{ secrets.GH_TOKEN }}
        with:
          jekyll_env: production
          jekyll_src: ""
          target_branch: "gh-pages"
